[tool.poetry]
name = "sifmiscadaproject"
version = "0.1.0"
description = ""
authors = ["LordJamesEsq <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
rioxarray = "^0.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
